// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/videostreaming.proto

package proto

type VideoRequest struct {
	VideoUrl        string `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	SegmentDuration int32  `protobuf:"varint,2,opt,name=segment_duration,json=segmentDuration,proto3" json:"segment_duration,omitempty"`
	OutputFormat    string `protobuf:"bytes,3,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	FilenamePrefix  string `protobuf:"bytes,4,opt,name=filename_prefix,json=filenamePrefix,proto3" json:"filename_prefix,omitempty"`
	Cleanup         bool   `protobuf:"varint,5,opt,name=cleanup,proto3" json:"cleanup,omitempty"`
	MaxDuration     int32  `protobuf:"varint,6,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
}

type VideoPartsResponse struct {
	Parts []string `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
}
